-- Schema principal do Backend Tecsys.
-- Execute este arquivo no SQL Editor do Supabase ou em um PostgreSQL local.

CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE IF NOT EXISTS usuarios (
    id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    senha_hash VARCHAR(255) NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP
);

CREATE TABLE IF NOT EXISTS perfis_rf (
    id_perfil_rf BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario BIGINT NOT NULL REFERENCES usuarios (id_usuario),
    nome VARCHAR(150) NOT NULL,
    modelo_gateway VARCHAR(150),
    frequencia_mhz DECIMAL(10, 3) NOT NULL,
    potencia_transmissao_dbm DECIMAL(8, 3) NOT NULL,
    sensibilidade_recepcao_dbm DECIMAL(8, 3) NOT NULL,
    alcance_estimado_m DECIMAL(12, 2),
    altura_gateway_m DECIMAL(8, 2),
    altura_dispositivo_m DECIMAL(8, 2),
    capacidade_max_equipamentos INT,
    quantidade_canais INT,
    limite_mensagens_transmissoes INT,
    periodo_limite_mensagens VARCHAR(30),
    custo_estimado_gateway DECIMAL(14, 2),
    caracteristicas_antena JSONB,
    considera_relevo BOOLEAN NOT NULL DEFAULT TRUE,
    considera_vegetacao BOOLEAN NOT NULL DEFAULT TRUE,
    considera_edificacoes BOOLEAN NOT NULL DEFAULT TRUE,
    considera_obstaculos BOOLEAN NOT NULL DEFAULT TRUE,
    parametros_adicionais JSONB,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP
);

CREATE TABLE IF NOT EXISTS criterios_instalacao (
    id_criterio_instalacao BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario BIGINT NOT NULL REFERENCES usuarios (id_usuario),
    nome VARCHAR(150) NOT NULL,
    descricao TEXT,
    tipos_elementos_permitidos JSONB,
    tipos_elementos_proibidos JSONB,
    requer_alimentacao_eletrica BOOLEAN,
    altura_minima_m DECIMAL(8, 2),
    distancia_maxima_ativos_m DECIMAL(12, 2),
    caracteristicas_minimas_local JSONB,
    locais_autorizados JSONB,
    locais_obrigatorios JSONB,
    locais_proibidos JSONB,
    limite_gateways INT,
    custo_maximo DECIMAL(14, 2),
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP
);

CREATE TABLE IF NOT EXISTS estudos (
    id_estudo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario BIGINT NOT NULL REFERENCES usuarios (id_usuario),
    tipo_delimitacao VARCHAR(30) NOT NULL,
    uf VARCHAR(2),
    municipio VARCHAR(120),
    bairro VARCHAR(120),
    geom GEOMETRY,
    nome VARCHAR(150) NOT NULL,
    descricao TEXT,
    distribuidora VARCHAR(150),
    versao_bdgd VARCHAR(100),
    nome_base_externa VARCHAR(255),
    tipos_ativo_selecionados JSONB,
    status VARCHAR(30) NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP
);

CREATE TABLE IF NOT EXISTS estudo_pontos (
    id_estudo_ponto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_estudo BIGINT NOT NULL REFERENCES estudos (id_estudo),
    origem VARCHAR(20) NOT NULL,
    id_ativo_bdgd VARCHAR(60),
    tipo_ativo VARCHAR(60),
    rotulo VARCHAR(150),
    papel VARCHAR(20) NOT NULL,
    prioridade VARCHAR(20),
    latitude DECIMAL(10, 7) NOT NULL,
    longitude DECIMAL(10, 7) NOT NULL,
    atributos JSONB,
    geom GEOMETRY,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cenarios (
    id_cenario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_estudo BIGINT NOT NULL REFERENCES estudos (id_estudo),
    id_perfil_rf BIGINT NOT NULL REFERENCES perfis_rf (id_perfil_rf),
    id_criterio_instalacao BIGINT REFERENCES criterios_instalacao (id_criterio_instalacao),
    id_cenario_base BIGINT REFERENCES cenarios (id_cenario),
    nome VARCHAR(150) NOT NULL,
    descricao TEXT,
    objetivo VARCHAR(40),
    status VARCHAR(30) NOT NULL,
    quantidade_gateways INT,
    pontos_interesse INT,
    pontos_cobertos INT,
    pontos_nao_cobertos INT,
    percentual_cobertura DECIMAL(5, 2),
    capacidade_utilizada_media_pct DECIMAL(5, 2),
    custo_total_estimado DECIMAL(14, 2),
    mancha_consolidada GEOMETRY,
    executado_em TIMESTAMP,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cenario_gateways (
    id_cenario_gateway BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cenario BIGINT NOT NULL REFERENCES cenarios (id_cenario),
    id_estudo_ponto BIGINT NOT NULL REFERENCES estudo_pontos (id_estudo_ponto),
    ordem INT,
    quantidade_pontos_atendidos INT,
    capacidade_utilizada_pct DECIMAL(5, 2),
    custo_estimado DECIMAL(14, 2),
    parametros_calculo JSONB,
    mancha_cobertura GEOMETRY
);

CREATE TABLE IF NOT EXISTS cenario_atendimentos (
    id_atendimento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cenario_gateway BIGINT NOT NULL REFERENCES cenario_gateways (id_cenario_gateway),
    id_estudo_ponto BIGINT NOT NULL REFERENCES estudo_pontos (id_estudo_ponto),
    distancia_m DECIMAL(12, 2),
    nivel_sinal_estimado_dbm DECIMAL(8, 3),
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (id_cenario_gateway, id_estudo_ponto)
);

CREATE INDEX IF NOT EXISTS idx_perfis_rf_id_usuario ON perfis_rf (id_usuario);
CREATE INDEX IF NOT EXISTS idx_criterios_instalacao_id_usuario ON criterios_instalacao (id_usuario);
CREATE INDEX IF NOT EXISTS idx_estudos_id_usuario ON estudos (id_usuario);
CREATE INDEX IF NOT EXISTS idx_estudo_pontos_id_estudo ON estudo_pontos (id_estudo);
CREATE INDEX IF NOT EXISTS idx_cenarios_id_estudo ON cenarios (id_estudo);
CREATE INDEX IF NOT EXISTS idx_cenario_gateways_id_cenario ON cenario_gateways (id_cenario);
